name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"  # Обновление раз в сутки
  workflow_dispatch:  # Возможность запустить вручную

permissions: write-all

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN_NEW1 }}
          base: header, repositories, metadata
          
          # 🎵 Подключаем Spotify
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: playlist
          plugin_music_limit: 5
          plugin_music_playlist: "1FulyKG2feuNE0bHGm9Al4"  # ⚠️ ИСПРАВЛЕНО!

          # 📢 Используем новый токен
          plugin_music_token: ${{ secrets.SPOTIFY_ACCESS_TOKEN }}
