name: Metrics
on:
  schedule: 
    - cron: "0 0 * * *" # Запуск каждый день в 00:00 UTC
  workflow_dispatch: # Позволяет запускать вручную

permissions: write-all  # ДАЁМ ПРАВА НА ЗАПИСЬ

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories, metadata
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 15
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_followup: yes
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_days: 30
          plugin_isocalendar: yes
          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_topics_sort: stars
