name: GitHub Profile Metrics

on:
  schedule:
    - cron: "0 * * * *" 
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}

          user: ArturPodchayev
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Tashkent

          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_threshold: 1%
          plugin_languages_sections: most-used

          plugin_followup: yes
          plugin_repositories: yes

          plugin_lines: yes
          plugin_traffic: yes

          # 🎧 Spotify (если хочешь потом добавить)
          # plugin_music: yes
          # plugin_music_provider: spotify
          # plugin_music_playlist: https://open.spotify.com/playlist/...
